server:
  port: 8081

spring:
  application:
    name: USER-SERVICE
  main:
    banner-mode: off
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    name: microservicetutorial
    url: jdbc:mysql://localhost:3306/microservicetutorial
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8085

# eureka:
#     instance:
#         prefer-ip-address: true
#     client:
#         fetch-registry: true
#         register-with-eureka: true
#         service-url:
#             dafaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      user-hotel-rating-breaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instance:
      user-hotel-rating-retry:
        max-attempts: 3
        wait-duration: 5s
  ratelimiter:
    instances:
      user-hotel-rate-limiter:
        limit-refresh-period: 5s
        limit-for-period: 4
        timeout-duration: 2s