server:
    port: 8083

spring:
    main:
        banner-mode: off
    output:
        ansi:
            enabled: ALWAYS
    data:
        mongodb:
            uri: mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+1.7.1
            database: microservicetutorial
    application:
        name: Rating-SERVICE

eureka:
    instance:
        prefer-ip-address: true
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            dafaultZone: http://localhost:8761/eureka